spring:
  datasource:
    driver-class-name: org.postgresql.Driver # PostgreSQL 데이터베이스 드라이버 설정
    url: jdbc:postgresql://localhost:5432/delivery # PostgreSQL 데이터베이스 연결 URL
    username: admin # DB 접속 계정명
    password: Group0000- # DB 접속 비밀번호

  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 자동으로 테이블을 업데이트
    show-sql: true # SQL 쿼리를 콘솔에 출력 (디버깅용)
    database: postgresql # JPA에서 사용할 데이터베이스를 PostgreSQL로 설정
    database-platform: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 최적화된 Hibernate Dialect 사용
    open-in-view: false # OSIV(Open Session In View) 비활성화 (성능 최적화를 위해 권장)
    generate-ddl: true # JPA가 자동으로 DDL 생성하도록 설정

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB